version: "3"
services:
        certbot:
                image: certbot/certbot
                container_name: certbot
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - ./etc:/etc/letsencrypt
                command:
                        - certonly
                        - --standalone
                        - -d
                        - ${DOMAIN}
                        - -m
                        - ${EMAIL}
                        - --agree-tos
                        - --non-interactive
